Added SampleCodes for leva+
InfosystemAGSwitzerland/StandardInterfaces pull request #13
Opened 2024-02-28 17:13 UTC by ISSBE

- added sample codes for leva+ as markdown file in examples subdirectory

2024-02-29 07:06 UTC, IS-MAU requested changes

2024-02-29 07:06 UTC, IS-MAU commented on Examples/IF2LEVASampleCodes.md
> +- `69510010`: Singel position
Sollte das nicht "Single" heissen?

2024-02-29 07:06 UTC, IS-MAU commented on Examples/IF2LEVASampleCodes.md
> +- `45420055`: Tractor unit with 8-axle semi low loader
Ich finde den Begriff "Tractor" komisch, klingt für mich wie ein John Deere. Wäre nicht "Semi truck" die bessere Übersetzung für Sattelschlepper, was diese nach meinem Verständnis sind

2024-03-06 10:26 UTC, ISSBE commented on Examples/IF2LEVASampleCodes.md
> +- `45420055`: Tractor unit with 8-axle semi low loader
gem. PO auf deutsche Werte umgestellt.

2024-03-06 10:26 UTC, ISSBE commented on Examples/IF2LEVASampleCodes.md
> +- `69510010`: Singel position
gem. PO auf deutsche Werte umgestellt.

2024-03-06 10:27 UTC, merged